### ISSUE TITLE
Problem with different branches for webhook

### ISSUE THREAD

**Issue by jacyuan** [auth0-extensions/auth0-gitlab-deploy#33]
Hello,

We're using the gitlab deployment extension of version 2.4.1 (with Node8 under auth0) for auto deployment.

In Auth0,  we installed and configured the extension with the use of the "master" branch in our git repo (GITLAB_BRANCH parameter). We then completed all other necessary configurations as asked in the tuto of Auth0 (The webhook has been added without specifying a specific branch=>all branch push should trigger the deployment). 
Everything works just fine with both manual deployment and webhook push event trigger.
In this case, I think/hope that all configurations are set correctly. 

Later, when we change the value of GITLAB_BRANCH parameter to "develop" (another existing branch under the same repo), with all other configurations stay untouched under auth0 and gitlab, the webhook trigger doesn't work any more. (the manual deployment still works)

A strange thing that we've observed under the auth0 log is that :

While using the "master" branch, when a webhook is triggered, we first see a "get access token" call 
“debug: Getting access token for xxxxxxxxxxxx/xxxx.eu.auth0.com”, 
before having the second one : “POST /ea4b1d92d987b09dda548b62d02952ca/api/deployments” for update.

But while using another branch different from the "master" one, no get access token call is invoked, but only a post for deployment is launched directly (and nothing happens after that, no change detection, no update, etc.).

Any ideas please ? Have I missed some steps ? 

Thank you very much.

yuan

**Comment by zxan1285** [comment]
hi @jacyuan 
I'm trying to reproduce this issue, but everything is working fine with my `dev` branch. Are you using `gitlab.com` or private gitlab instance?

Also, `POST /ea4b1d92d987b09dda548b62d02952ca/api/deployments` is for manual deploy, which is using admin's token for interacting with API. That's why it does not trying to get another token.

**Comment by jacyuan** [comment]
Hello @zxan1285 ,

Thank you for your reply.
Indeed. After having changed to another test account in gitlab.com, with a new test repo, everything's working fine now.

I think there could have something to do with the old repository, which is an imported one from BitBucket...I'm not sure. Gonna check that in detail later.

Thank you very much
yuan
