### ISSUE TITLE
Schema Validation Failed

### ISSUE THREAD

**Issue by zikes** [auth0-extensions/auth0-gitlab-deploy#38]
While trying to run a deployment, I get the following error:

```
Schema validation failed loading [
    {
        "keyword": "required",
        "dataPath": ".emailProvider",
        "schemaPath": "#/properties/emailProvider/required",
        "params": {
            "missingProperty": "name"
        },
        "message": "should have required property 'name'"
    }
]
```

My repository does not have an `emails` folder for email providers, and nothing else was changed except some minor HTML edits on existing pages.

With some research, I found that this repository's `package.json` file imports `auth0-source-control-extension-tools` but not at any specific version. After reviewing that repository, I found that it recently updated to include some schema validation code, which I believe to be causing this issue.

**Comment by fyockm** [comment]
@zikes we found (and replaced) a missing module in the underlying webtask stack. this should now be fixed. please reopen if that's not the case.
